name: Docker Image 

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master, actions ]

env:
  IMAGE_NAME: eth-bsc-bridge-relayer:latest 
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t $IMAGE_NAME

    - name: Azure login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: veriori.azurecr.io

    - name: Push image 
      run: docker push $IMAGE_NAME
